name: Deployment From Github To AWS
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker-compose -f docker-compose-dev.yaml up


      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: dockerTest
          environment_name: Dockertest-env
          existing_bucket_name: elasticbeanstalk-us-east-1-315865595366
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
